from aerospike_ui_api.models.cluster import (
    ClusterInfo,
    ClusterNode,
    NamespaceInfo,
    SetInfo,
)

mock_clusters: dict[str, ClusterInfo] = {
    "conn-1": ClusterInfo(
        connectionId="conn-1",
        nodes=[
            ClusterNode(
                name="BB9060016AE4202",
                address="127.0.0.1",
                port=3000,
                build="8.1.0.0",
                edition="Aerospike Community Edition",
                clusterSize=1,
                uptime=864000,
                clientConnections=24,
                statistics={
                    "cluster_key": "5A7E2B3C",
                    "cluster_integrity": "true",
                    "cluster_is_member": "true",
                    "total_rw_errors": 0,
                    "stat_read_reqs": 125340,
                    "stat_read_success": 125280,
                    "stat_write_reqs": 67890,
                    "stat_write_success": 67850,
                    "batch_index_initiate": 4520,
                    "scan_aggr_complete": 12,
                    "query_reqs": 340,
                    "query_success": 338,
                    "heap_allocated_kbytes": 32768,
                    "heap_active_kbytes": 28672,
                    "heap_mapped_kbytes": 65536,
                    "fabric_connections": 0,
                    "heartbeat_connections": 0,
                    "info_queue": 0,
                    "migrate_partitions_remaining": 0,
                },
            ),
        ],
        namespaces=[
            NamespaceInfo(
                name="test",
                objects=80,
                memoryUsed=52428800,
                memoryTotal=1073741824,
                memoryFreePct=95,
                deviceUsed=20971520,
                deviceTotal=4294967296,
                replicationFactor=1,
                stopWrites=False,
                hwmBreached=False,
                highWaterMemoryPct=80,
                highWaterDiskPct=80,
                sets=[
                    SetInfo(
                        name="users",
                        namespace="test",
                        objects=50,
                        tombstones=0,
                        memoryDataBytes=32768000,
                        stopWritesCount=0,
                    ),
                    SetInfo(
                        name="products",
                        namespace="test",
                        objects=30,
                        tombstones=0,
                        memoryDataBytes=19660800,
                        stopWritesCount=0,
                    ),
                ],
            ),
        ],
    ),
    "conn-2": ClusterInfo(
        connectionId="conn-2",
        nodes=[
            ClusterNode(
                name="BB9060016AE4301",
                address="10.0.1.10",
                port=3000,
                build="7.2.0.2",
                edition="Aerospike Enterprise Edition",
                clusterSize=3,
                uptime=2592000,
                clientConnections=42,
                statistics={
                    "cluster_key": "A3F19B2D",
                    "cluster_integrity": "true",
                    "cluster_is_member": "true",
                    "total_rw_errors": 3,
                    "stat_read_reqs": 1540200,
                    "stat_read_success": 1539800,
                    "stat_write_reqs": 892100,
                    "stat_write_success": 892050,
                    "batch_index_initiate": 28400,
                    "scan_aggr_complete": 85,
                    "query_reqs": 2100,
                    "query_success": 2098,
                    "heap_allocated_kbytes": 131072,
                    "heap_active_kbytes": 114688,
                    "heap_mapped_kbytes": 262144,
                    "fabric_connections": 4,
                    "heartbeat_connections": 2,
                    "info_queue": 0,
                    "migrate_partitions_remaining": 0,
                },
            ),
            ClusterNode(
                name="BB9060016AE4302",
                address="10.0.1.11",
                port=3000,
                build="7.2.0.2",
                edition="Aerospike Enterprise Edition",
                clusterSize=3,
                uptime=2591500,
                clientConnections=38,
                statistics={
                    "cluster_key": "A3F19B2D",
                    "cluster_integrity": "true",
                    "cluster_is_member": "true",
                    "total_rw_errors": 1,
                    "stat_read_reqs": 1520100,
                    "stat_read_success": 1519700,
                    "stat_write_reqs": 880300,
                    "stat_write_success": 880260,
                    "batch_index_initiate": 27800,
                    "scan_aggr_complete": 82,
                    "query_reqs": 2050,
                    "query_success": 2049,
                    "heap_allocated_kbytes": 131072,
                    "heap_active_kbytes": 110592,
                    "heap_mapped_kbytes": 262144,
                    "fabric_connections": 4,
                    "heartbeat_connections": 2,
                    "info_queue": 0,
                    "migrate_partitions_remaining": 0,
                },
            ),
            ClusterNode(
                name="BB9060016AE4303",
                address="10.0.1.12",
                port=3000,
                build="7.2.0.2",
                edition="Aerospike Enterprise Edition",
                clusterSize=3,
                uptime=2590000,
                clientConnections=35,
                statistics={
                    "cluster_key": "A3F19B2D",
                    "cluster_integrity": "true",
                    "cluster_is_member": "true",
                    "total_rw_errors": 2,
                    "stat_read_reqs": 1498500,
                    "stat_read_success": 1498100,
                    "stat_write_reqs": 870200,
                    "stat_write_success": 870150,
                    "batch_index_initiate": 27200,
                    "scan_aggr_complete": 80,
                    "query_reqs": 1980,
                    "query_success": 1978,
                    "heap_allocated_kbytes": 131072,
                    "heap_active_kbytes": 108544,
                    "heap_mapped_kbytes": 262144,
                    "fabric_connections": 4,
                    "heartbeat_connections": 2,
                    "info_queue": 0,
                    "migrate_partitions_remaining": 0,
                },
            ),
        ],
        namespaces=[
            NamespaceInfo(
                name="staging",
                objects=200,
                memoryUsed=536870912,
                memoryTotal=4294967296,
                memoryFreePct=87,
                deviceUsed=1073741824,
                deviceTotal=17179869184,
                replicationFactor=2,
                stopWrites=False,
                hwmBreached=False,
                highWaterMemoryPct=80,
                highWaterDiskPct=80,
                sets=[
                    SetInfo(
                        name="orders",
                        namespace="staging",
                        objects=200,
                        tombstones=3,
                        memoryDataBytes=536870912,
                        stopWritesCount=0,
                    ),
                ],
            ),
        ],
    ),
}
